---
simulation_param:
  dt: 0.2

# scale_rob: if True, the robustness value is scaled by the maximum robustness value
scale_rob:
  True

road_network_param:
  num_chankins_corner_cutting: 1
  polyline_resampling_step: 0.5
  merging_length: 10000

# t_react: reaction time of the ego vehicle, can be manipulated to see the effect of reaction time on the safe distance
ego_vehicle_param:
  vehicle_number: 2
  v_max: 60
  a_max: 5.0
  a_min: -10.5
  j_max: 10
  j_min: -10
  v_des: 30
  t_react: 
  dynamics_param: None
  fov: 200
  v_min: 0
  const_dist_offset: 0
  emergency_profile: []
  fov_speed_limit: 50
  braking_speed_limit: 43
  road_condition_speed_limit: 51

other_vehicles_param:
  # vehicle_number: 2
  # v_max: 60
  # v_min: 0
  # a_max: 5
   a_min: -10.5
  # j_max: 10
  # j_min: -10
  # t_react: 0.4
  # dynamics_param: None

# # traffic_rules_param:
# j_abrupt: -2 
# a_abrupt: -2
# standstill_error: 0.01
# min_velocity_dif: 15
# num_veh_congestion: 3
# max_congestion_velocity: 2.78
# num_veh_slow_moving_traffic: 3
# max_slow_moving_traffic_velocity: 8.33
# num_veh_queue_of_vehicles: 3
# max_queue_of_vehicles_velocity: 3
# max_velocity_limit_free_driving: 16.67
# desired_interstate_velocity: 36.11
# min_interstate_width: 7.0
# close_to_lane_border: 0.2
# close_to_other_vehicle: 0.5
# slightly_higher_speed_difference: 5.55
# u_turn: 1.57
# country: DEU
# above_centerline_th: 0.1
# max_interstate_speed_truck: 22.22
# d_sl: 1.0