---
road_network_param:
  num_chankins_corner_cutting: 1
  polyline_resampling_step: 0.5
  merging_length: 10000

critical_param:
  critical_distance: 10 # for SD
  critical_speed: 5.56 # for MSL, TF
  critical_acceleration: 3 # UB