#pragma once
#define RAYTRACE_DEBUG 0

#ifndef ENABLE_SERIALIZER
#define ENABLE_SERIALIZER 1
#endif

#if ENABLE_SERIALIZER
#define SERIALIZER_DEFAULT_FORMAT "compact"
#endif

#ifndef ENABLE_TRIANGULATION
#define ENABLE_TRIANGULATION 1
#endif

#ifndef ENABLE_GPC
#define ENABLE_GPC 1
#endif

#ifndef ENABLE_POLYGON_VALIDITY_CHECKS
#define ENABLE_POLYGON_VALIDITY_CHECKS 0
#endif
