#ifndef CPP_COLLISION_INCLUDE_COLLISION_SOLVERS_BOOST_BOOST_ENTITY_TYPE_H_
#define CPP_COLLISION_INCLUDE_COLLISION_SOLVERS_BOOST_BOOST_ENTITY_TYPE_H_

namespace collision {
namespace solvers {
namespace solverBoost {
enum BOOST_COLLISION_ENTITY_TYPE {
  BOOST_COLLISION_ENTITY_TYPE_INVALID = -1,
  BOOST_COLLISION_ENTITY_TYPE_UNKNOWN = 0,
  COLLISION_ENTITY_TYPE_BOOST_OBJECT = 200,
};
}
}  // namespace solvers
}  // namespace collision

#endif /* CPP_COLLISION_INCLUDE_COLLISION_SOLVERS_BOOST_BOOST_ENTITY_TYPE_H_ \
        */
