name: MacOS 11 Workflow
on: [workflow_dispatch]

jobs:
  macos-workflow:
    runs-on: macos-11

    steps:
    
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '12.4'
      - name: install dependencies
        run: |
          brew install cmake eigen boost
          wget https://mac.r-project.org/openmp/openmp-10.0.0-darwin17-Release.tar.gz
          tar -xvzf openmp-10.0.0-darwin17-Release.tar.gz
          cp -R usr /
      - uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"
      - name: Build wheel Python 3.7
        run: |
          ./.github/workflows/build_wheel_37_macos.sh
          
      - name: Test wheel Python 3.7
        run: |
          ./.github/workflows/test_wheel_37_macos.sh
      
      - name: Build wheel Python 3.8
        run: |
          ./.github/workflows/build_wheel_38_macos.sh
      
      - name: Build wheel Python 3.9
        run: |
          ./.github/workflows/build_wheel_39_macos.sh
      
      - name: Test wheel Python 3.8
        run: |
          ./.github/workflows/test_wheel_38_macos.sh
          
      - name: Test wheel Python 3.9
        run: |
          ./.github/workflows/test_wheel_39_macos.sh
      
      - name: Archive build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: |
            dist
