
#ifndef CPP_TESTS_COLLISION_OFFLINE_TESTS_COLLISION_TESTS_H_
#define CPP_TESTS_COLLISION_OFFLINE_TESTS_COLLISION_TESTS_H_

namespace test {
int test_polygon(void);
}

#endif /* CPP_TESTS_COLLISION_OFFLINE_TESTS_COLLISION_TESTS_H_ */
